// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SailView.Data;

#nullable disable

namespace SailView.Migrations
{
    [DbContext(typeof(SailAppDbContext))]
    [Migration("20230126185600_racestbl")]
    partial class racestbl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SailView.Data.Models.BoatDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BoatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SailNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoatDetail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoatName = "Asterix",
                            BoatType = "1720",
                            CreatedDate = new DateTime(2023, 1, 26, 18, 56, 0, 270, DateTimeKind.Local).AddTicks(4025),
                            SailNumber = "IRL123"
                        });
                });

            modelBuilder.Entity("SailView.Data.Models.Races", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BoatDetailsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RaceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RacePosition")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("RaceTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("BoatDetailsId");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("SailView.Data.Models.Races", b =>
                {
                    b.HasOne("SailView.Data.Models.BoatDetails", "BoatDetails")
                        .WithMany()
                        .HasForeignKey("BoatDetailsId");

                    b.Navigation("BoatDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
