// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SailView.Data;

#nullable disable

namespace SailView.Migrations
{
    [DbContext(typeof(SailAppDbContext))]
    [Migration("20230216215713_NewProperty")]
    partial class NewProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SailView.Data.Models.BoatDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BoatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SailNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoatDetail");
                });

            modelBuilder.Entity("SailView.Data.Models.BoatRaces", b =>
                {
                    b.Property<int>("BoatId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("FinishingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimingRecord")
                        .HasColumnType("time");

                    b.HasKey("BoatId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("BoatRace");
                });

            modelBuilder.Entity("SailView.Data.Models.Races", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BoatDetailsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RaceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RacePosition")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("RaceTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("SailView.Data.Models.BoatRaces", b =>
                {
                    b.HasOne("SailView.Data.Models.BoatDetails", "BoatDetails")
                        .WithMany("BoatRaces")
                        .HasForeignKey("BoatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SailView.Data.Models.Races", "Races")
                        .WithMany("BoatRaces")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoatDetails");

                    b.Navigation("Races");
                });

            modelBuilder.Entity("SailView.Data.Models.BoatDetails", b =>
                {
                    b.Navigation("BoatRaces");
                });

            modelBuilder.Entity("SailView.Data.Models.Races", b =>
                {
                    b.Navigation("BoatRaces");
                });
#pragma warning restore 612, 618
        }
    }
}
