// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SailView.Data;

#nullable disable

namespace SailView.Migrations
{
    [DbContext(typeof(SailAppDbContext))]
    [Migration("20230209171225_newProp")]
    partial class newProp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BoatDetailsRaces", b =>
                {
                    b.Property<int>("BoatDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("BoatDetailsId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("BoatDetailsRaces");
                });

            modelBuilder.Entity("SailView.Data.Models.BoatDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BoatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SailNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoatDetail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoatName = "Asterix",
                            BoatType = "1720",
                            CreatedDate = new DateTime(2023, 2, 9, 17, 12, 25, 411, DateTimeKind.Local).AddTicks(2138),
                            SailNumber = "IRL123"
                        });
                });

            modelBuilder.Entity("SailView.Data.Models.Races", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BoatDetailsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RaceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RacePosition")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("RaceTime")
                        .HasColumnType("time");

                    b.Property<bool>("ShowBoatDetails")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("BoatDetailsRaces", b =>
                {
                    b.HasOne("SailView.Data.Models.BoatDetails", null)
                        .WithMany()
                        .HasForeignKey("BoatDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SailView.Data.Models.Races", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
